const fs = require('fs');

const frPath = './src/locales/fr.json';
const arPath = './src/locales/ar.json';

const fr = JSON.parse(fs.readFileSync(frPath, 'utf8'));
const ar = JSON.parse(fs.readFileSync(arPath, 'utf8'));

const modalsFr = {
  "quickCreate": "Menu de Création Rapide",
  "payment": "Enregistrer un Paiement",
  "absence": "Signaler une Absence",
  "student": "Nouvelle Inscription",
  "teacher": "Ajouter un Enseignant",
  "employee": "Ajouter un Employé",
  "parent": "Ajouter un Parent",
  "message": "Nouveau Message",
  "bulletin": "Générer Bulletins",
  "course": "Planifier un cours",
  "newSchool": "Créer un Établissement",
  "class": "Créer une Classe",
  "close": "Fermer",
  "cancel": "Annuler",
  "create": "Créer",
  "save": "Enregistrer",
  "submit": "Valider",
  "quick_student_title": "Nouvel Élève",
  "quick_student_desc": "Inscrire un étudiant.",
  "quick_payment_title": "Encaisser Paiement",
  "quick_payment_desc": "Frais de scolarité.",
  "quick_message_title": "Nouveau Message",
  "quick_message_desc": "Contacter les parents.",
  "quick_bulletin_title": "Nouveau Bulletin",
  "quick_bulletin_desc": "Générer des notes.",
  "quick_class_title": "Nouvelle Classe",
  "quick_class_desc": "Ajouter une classe.",
  "school_name": "Nom du nouvel établissement",
  "class_name": "Nom de la classe",
  "class_level": "Niveau",
  "student_select": "Élève",
  "motif": "Motif",
  "amount": "Montant (FCFA)",
  "payment_method": "Mode de paiement",
  "recipient": "Destinataire(s)",
  "subject": "Sujet",
  "message_body": "Message",
  "send": "Envoyer",
  "student_concerned": "Élève concerné",
  "date": "Date",
  "duration": "Durée / Heure",
  "absence_motif": "Motif",
  "comments": "Commentaire (Optionnel)",
  "save_absence": "Enregistrer l'absence",
  "student_info": "1. Informations de l'Élève",
  "last_name": "Nom",
  "first_name": "Prénom(s)",
  "birth_date": "Date de Naissance",
  "class_assign": "Classe (Affectation)",
  "email": "Email",
  "password_default": "Mot de passe (par défaut: passer123)",
  "parent_info": "2. Informations du Parent / Tuteur",
  "parent_last_name": "Nom du parent",
  "parent_first_name": "Prénom du parent",
  "phone": "Téléphone",
  "fees_info": "3. Frais d'Inscription & Scolarité",
  "reg_fee_amount": "Montant des frais d'inscription (CFA)",
  "status": "Statut",
  "complete_registration": "Valider l'inscription complète",
  "password_optional": "Mot de passe (facultatif)",
  "taught_subject": "Matière enseignée",
  "role": "Poste / Rôle",
  "link_to_student": "Lier à un élève (Matricule ou Nom)",
  "create_profile": "Créer le profil",
  "eval_name": "Nom de l'évaluation",
  "eval_type": "Type d'évaluation",
  "max_score": "Noté sur (Maximum)",
  "create_eval": "Créer l'évaluation",
  "term": "Trimestre/Semestre",
  "generate": "Lancer la génération",
  "date_time": "Date et Heure",
  "plan": "Planifier",
  "day": "Jour",
  "start_time": "Heure de début",
  "end_time": "Heure de fin",
  "save_course": "Enregistrer le cours",
  "doc_type": "Type de document",
  "doc_name": "Nom du document",
  "file": "Fichier (PDF, JPG, PNG)",
  "uploading": "Envoi en cours...",
  "add_annex": "Ajouter aux annexes",
  "attachments": "Fichiers joints",
  "view": "Voir",
  "no_doc": "Aucun document n'a été ajouté pour cet élève.",
  "close_dossier": "Fermer le dossier"
};

const modalsAr = {
  "quickCreate": "قائمة الإنشاء السريع",
  "payment": "تسجيل الدفع",
  "absence": "الإبلاغ عن غياب",
  "student": "تسجيل جديد",
  "teacher": "إضافة معلم",
  "employee": "إضافة موظف",
  "parent": "إضافة ولي أمر",
  "message": "رسالة جديدة",
  "bulletin": "إنشاء كشوف الدرجات",
  "course": "جدولة درس",
  "newSchool": "إنشاء مؤسسة",
  "class": "إنشاء قسم",
  "close": "إغلاق",
  "cancel": "إلغاء",
  "create": "إنشاء",
  "save": "حفظ",
  "submit": "تأكيد",
  "quick_student_title": "طالب جديد",
  "quick_student_desc": "تسجيل طالب.",
  "quick_payment_title": "تحصيل الدفع",
  "quick_payment_desc": "الرسوم الدراسية.",
  "quick_message_title": "رسالة جديدة",
  "quick_message_desc": "التواصل مع أولياء الأمور.",
  "quick_bulletin_title": "كشف درجات جديد",
  "quick_bulletin_desc": "إصدار الدرجات.",
  "quick_class_title": "قسم جديد",
  "quick_class_desc": "إضافة قسم.",
  "school_name": "اسم المؤسسة الجديدة",
  "class_name": "اسم القسم",
  "class_level": "المستوى",
  "student_select": "الطالب",
  "motif": "السبب",
  "amount": "المبلغ (فرنك أفريقي)",
  "payment_method": "طريقة الدفع",
  "recipient": "المستلم (ون)",
  "subject": "الموضوع",
  "message_body": "الرسالة",
  "send": "إرسال",
  "student_concerned": "الطالب المعني",
  "date": "التاريخ",
  "duration": "المدة / الوقت",
  "absence_motif": "سبب الغياب",
  "comments": "تعليق (اختياري)",
  "save_absence": "حفظ الغياب",
  "student_info": "1. معلومات الطالب",
  "last_name": "الاسم العائلي",
  "first_name": "الاسم الشخصي",
  "birth_date": "تاريخ الميلاد",
  "class_assign": "القسم (التعيين)",
  "email": "البريد الإلكتروني",
  "password_default": "كلمة المرور (الافتراضية: passer123)",
  "parent_info": "2. معلومات ولي الأمر / الوصي",
  "parent_last_name": "الاسم العائلي لولي الأمر",
  "parent_first_name": "الاسم الشخصي لولي الأمر",
  "phone": "رقم الهاتف",
  "fees_info": "3. رسوم التسجيل والدراسة",
  "reg_fee_amount": "مبلغ رسوم التسجيل (فرنك أفريقي)",
  "status": "الحالة",
  "complete_registration": "تأكيد التسجيل الكامل",
  "password_optional": "كلمة المرور (اختياري)",
  "taught_subject": "المادة المدرسة",
  "role": "المنصب / الدور",
  "link_to_student": "الربط بطالب (رقم التسجيل أو الاسم)",
  "create_profile": "إنشاء الملف الشخصي",
  "eval_name": "اسم التقييم",
  "eval_type": "نوع التقييم",
  "max_score": "الدرجة القصوى",
  "create_eval": "إنشاء التقييم",
  "term": "الفصل/السداسي",
  "generate": "بدء الإنشاء",
  "date_time": "التاريخ والوقت",
  "plan": "جدولة",
  "day": "اليوم",
  "start_time": "وقت البدء",
  "end_time": "وقت الانتهاء",
  "save_course": "حفظ الدرس",
  "doc_type": "نوع المستند",
  "doc_name": "اسم المستند",
  "file": "الملف (PDF، JPG، PNG)",
  "uploading": "جاري الإرسال...",
  "add_annex": "إضافة إلى الملحقات",
  "attachments": "الملفات المرفقة",
  "view": "عرض",
  "no_doc": "لم يتم إضافة أي مستند لهذا الطالب.",
  "close_dossier": "إغلاق الملف"
};

fr.admin.modals = modalsFr;
ar.admin.modals = modalsAr;

fs.writeFileSync(frPath, JSON.stringify(fr, null, 2));
fs.writeFileSync(arPath, JSON.stringify(ar, null, 2));

console.log("Modals added to JSON successfully!");
