-- Migration: Add bulletin customization and school design settings to school_settings
ALTER TABLE IF EXISTS public.school_settings
ADD COLUMN IF NOT EXISTS bulletin_template VARCHAR(50) DEFAULT 'classic',
ADD COLUMN IF NOT EXISTS bulletin_title VARCHAR(255) DEFAULT 'BULLETIN TRIMESTRIEL DE NOTES',
ADD COLUMN IF NOT EXISTS ministry_header VARCHAR(500) DEFAULT 'MINISTERE DE L''EDUCATION NATIONALE ET DE L''ALPHABETISATION',
ADD COLUMN IF NOT EXISTS dren_name VARCHAR(255) DEFAULT 'DREN DIVO',
ADD COLUMN IF NOT EXISTS school_statut VARCHAR(100) DEFAULT 'Privé',
ADD COLUMN IF NOT EXISTS show_student_photo BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS show_rank BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS show_class_stats BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS show_teacher_names BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS show_honor_roll BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS show_signatures BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS bulletin_color VARCHAR(50) DEFAULT '#1e3a8a',
ADD COLUMN IF NOT EXISTS stamp_url TEXT DEFAULT NULL;
